### ISSUE TITLE
Doesn't crawl at all

### ISSUE THREAD

**Issue by g00g1** [mwmbl/crawler-extension#24]
See screenshot attached.
![2022-06-13_14:07:31](https://user-images.githubusercontent.com/91201021/173341231-a4659660-730d-4a1d-89bf-41380e30b77b.png)

**Comment by ColinEspinas** [comment]
Hello @g00g1,
we are gonna need a bit more details, what is the environment you are having this bug in? Which Firefox version? Which OS are you running?

Do you have any errors in the console?

**Comment by g00g1** [comment]
No errors in the console

![2022-06-14_11:38:56](https://user-images.githubusercontent.com/91201021/173533790-20a341c8-e9c9-4523-b646-2d281ed302b5.png)
![2022-06-14_11:36:16](https://user-images.githubusercontent.com/91201021/173533795-2b5c5158-4503-45e0-ae0e-5d255b3e8d37.png)

**Comment by daoudclarke** [comment]
Hi @g00g1 is this still an issue for you in the latest version? We've had numerous updates since you reported the bug.

**Comment by g00g1** [comment]
Haven't checked. I need to update firefox to install the latest version. I will test it a bit later

**Comment by daoudclarke** [comment]
Ah, there was a bug with old Firefox versions where it would not crawl at all, so I suspect that may be your issue.

**Comment by g00g1** [comment]
I have updated to the latest esr release available at the Gentoo repository, 91.11esr does not support this addon :(

Can't check whether it was fixed for me, but I won't have any possibility to check in nearest time, so I am closing this issue.
