### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by adjagu** [mwmbl/crawler-extension#27]
Issue: Build failed when following the "[How to build](README.md#how-to-build)" section of `README.md`.

Steps to reproduce:
1. `git clone https://github.com/mwmbl/crawler-extension`
2. `cd crawler-extension`
3. `npm run build`

Output:
```
> mwmbl-crawler-extension@0.0.0 build
> vite build
/tmp/build-ddf9cdff.sh: line 1: vite: command not found
```

System Information:
- NPM v8.14.0
- NodeJS v18.6.0
- OS: EndeavourOS
- Kernel: 5.18.12-zen1-1-zen

I'm probably missing something obvious.

**Comment by ColinEspinas** [comment]
Hello @AdJaGu, did you run `npm install` before trying to build the project?

**Comment by adjagu** [comment]
@ColinEspinas No I did not. I have now though. Ran `npm install` as new step 3 and then `npm run build` after and it worked.

Maybe something could be added to the "[How to build](README.md#how-to-build)" section for others like me?

1. `git clone https://github.com/mwmbl/crawler-extension`
2. `cd crawler-extension`
3. `npm install`
4. `npm run build`

**Comment by adjagu** [comment]
Closing because this issue is resolved. Thank you for your assistance @ColinEspinas.
