### ISSUE TITLE
add websites to the crawler 

### ISSUE THREAD

**Issue by nobaraos12** [mwmbl/crawler-extension#34]
a request for the following sites to be added to the crawler 

- [codeberg](https://codeberg.org/)
- [lemmy.ml](https://lemmy.ml/)
- [blue flashcards](https://freezingblue.com/flashcards/)
- [odysee](https://odysee.com/)
- [kutt it ](https://kutt.it/)
- [ocean of pdf ](https://oceanofpdf.com/)

**Comment by daoudclarke** [comment]
This needs to be done on the main repo, I created an issue here: https://github.com/mwmbl/mwmbl/issues/79
