### ISSUE TITLE
Replace the generic extension icon with official branding one on AMO

### ISSUE THREAD

**Issue by omasanori** [mwmbl/crawler-extension#38]
The current status:

![IMG_20221225_081118.jpg](https://user-images.githubusercontent.com/167209/209453035-425503be-c8be-4459-96d4-8c3925c80ec7.jpg)

The green default icon should be replaced with the project's icon.

**Comment by daoudclarke** [comment]
![Screenshot from 2022-12-26 22-53-36](https://user-images.githubusercontent.com/1283077/209587341-2c845c83-82ab-4c80-973f-cee3cd63bbfa.png)

Done!

**Comment by ColinEspinas** [comment]
@daoudclarke Seems like the icon you added is not the official mwmbl logo.

**Comment by daoudclarke** [comment]
Oops, seems like I found an old one 😂

**Comment by ColinEspinas** [comment]
Up @daoudclarke, seems like you forgot to change it 😄

**Comment by daoudclarke** [comment]
![image](https://github.com/mwmbl/crawler-extension/assets/1283077/9a92d6a5-07be-4d14-a79b-243a85eb1b92)

Hopefully I got it right this time :sweat_smile:
